baseurl = "http://jomogoon.github.io"
languageCode = "ko-kr"
title = "LifeLog"
paginate = 5
#theme = "hugo-theme-air"
theme = "hugo-theme-blueberry-detox"
canonifyurls = true
author = "jomogoon"

[permalinks]
  post = "/blog/:slug/"

[indexes]
  category = "categories"
  tag = "tags"

