baseurl = "http://jomogoon.github.io"
languageCode = "ko-kr"
title = "Daily Log"
theme = "angels-ladder" # 相対パスではなく baseurl を基点とした絶対パスにする
canonifyurls = true

[params]
  description = "This is log"
  author = "jomogoon"

[permalinks]
  post = "/:slug/"

[indexes]
  category = "categories"
  tag = "tags"


